name: Build and deploy site to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        run: |
          # Use a known released Quarto version; update if a newer pinned version is desired
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.537/quarto-1.4.537-linux-amd64.deb -O quarto.deb
          sudo apt install -y ./quarto.deb

      - name: Render site
        run: quarto render

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site